### ISSUE TITLE
msgpack and nested serialization

### ISSUE THREAD

**Issue by adsharma** [yukinarit/pyserde#76] opened 2021-01-14 00:12 UTC
Trying to figure out how to resolve this problem:

```
>>> from serde.msgpack import from_msgpack, to_msgpack
>>> from simpleRaft.messages.append_entries import AppendEntriesMessage, LogEntry
>>> a = LogEntry(term=0)

# Can serialize LogEntry below

>>> to_msgpack(a)
b'\x85\xa4term\x00\xa5index\x00\xa7command\x00\xa3key\xc0\xa5value\xc0'

# Just not when it's nested in another serializable object

>>> b = AppendEntriesMessage(sender=1, receiver=2, term=3, entries=[a])
>>> to_msgpack(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arun/.local/lib/python3.8/site-packages/pyserde-0.2.1-py3.8.egg/serde/msgpack.py", line 34, in to_msgpack
    return se.serialize(obj, **opts)
  File "/home/arun/.local/lib/python3.8/site-packages/pyserde-0.2.1-py3.8.egg/serde/msgpack.py", line 23, in serialize
    return msgpack.packb(maybe_ext, use_bin_type=use_bin_type, **opts)
  File "/home/arun/.local/lib/python3.8/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 286, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 258, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 283, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'LogEntry' object
```

**Comment by yukinarit** [comment] 2021-01-14 12:52
Hi! 

Looks like the error is coming from `msgpack` library, not pyserde 🤔 

Is [this](https://github.com/adsharma/raft/blob/master/simpleRaft/messages/append_entries.py#L10-L36) the code?

**Comment by adsharma** [comment] 2021-01-14 15:19
Yes, that's the code that triggered the error.
I have found a workaround for now (do it manually before calling pyserde).
But would love to understand why the nested case isn't working for msgpack.
Based in the pyserde docs, it's working for the json case?

**Comment by yukinarit** [comment] 2021-01-16 11:13
@adsharma  
Sorry for the delay! Just merged a PR that adds more tests.

Nested dataclass like [this](https://github.com/yukinarit/pyserde/blob/master/tests/test_basics.py#L119-L129) is supported from the very beginning and I use it heavily in my private project!

I am happy to help you to debug and investigate the cause! 🙂 
Can you please share how to reproduce the error?

**Comment by adsharma** [comment] 2021-01-16 23:57
Setup.py install the git repo you found and then run the 3-4 commands I
pasted.

I'm away on a vacation and not near a computer. Let me know if it doesn't
reproduce for you in the next couple of days.

**Comment by yukinarit** [comment] 2021-01-17 07:05
OK, If I make the following changes, it work.

* Add  element type to `entries: List[LogEntry] = ...`
* Move LogEntry up in `append_entries.py`

```python
class Command(IntEnum):
    PUT = 0
    GET = 1


@deserialize
@serialize
@dataclass
class LogEntry:
    _type = BaseMessage.MessageType.LogEntry

    term: int
    index: int = 0
    command: Command = Command.PUT
    key: Union[int, str, None] = None
    value: Union[int, str, None] = None


@deserialize
@serialize
@dataclass
class AppendEntriesMessage(BaseMessage):
    _type = BaseMessage.MessageType.AppendEntries

    leader_id: Optional[str] = None
    prev_log_index: int = 0
    prev_log_term: int = 0
    entries: List[LogEntry] = field(default_factory=list)
    leader_commit: int = 0

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseMessage.EXT_DICT[LogEntry._type] = LogEntry # type: ignore
```

So the problem was in pyserde which doesn't support deserializing nested dataclass with bare `List` type annotation! OK, I will try to fix pyserde.

**Comment by yukinarit** [comment] 2021-01-19 12:00
Hi, I checked the code but I think pyserde is unable to deserialize if no element type is specified like `List`. It needs to be like `List[LogEntry]`

**Comment by adsharma** [comment] 2021-01-20 02:48
Thanks for debugging this! I'll update the code as suggested by you.

Perhaps pyserde can detect this case and error out in a more predictable
way.

The reason why I used List instead of List[LogEntry] is that I wanted
implementations to be able to customize LogEntry.

Does pyserde support python's protocols? I guess if I have two apps:

App1LogEntry
App2LogEntry

how would I go about using pyserde?

**Comment by yukinarit** [comment] 2021-01-20 11:49
> Perhaps pyserde can detect this case and error out in a more predictable way. 

True! I will fix pyserde to raise an error for such case.

**Comment by yukinarit** [comment] 2022-03-21 15:37
I guess it's already resolved? 🤔  Please reopen if you need further help, thanks.

**Closed by yukinarit** 2022-03-21 15:37 UTC
